/**
 * List of rtk enums
 *
 * @module RTKEnums
 * @category Enums
 *
 */

/**
 * List of RTK Cache tags
 *
 * @see https://redux-toolkit.js.org/rtk-query/usage/cache-behavior
 */
export enum CACHE_TAG {
  ACCOUNT = 'ACCOUNT',
  ACCOUNT_ADDRESS = 'ACCOUNT_ADDRESS',
  ACCOUNT_SUBSCRIPTION = 'ACCOUNT_SUBSCRIPTION',

  USER_PAYMENT_METHODS = 'USER_PAYMENT_METHODS',
  USER_INVOICES = 'USER_INVOICES',
  CATEGORIES = 'CATEGORIES',
  CLASSIFICATIONS = 'CLASSIFICATIONS',
  EVENTS = 'EVENTS',
  MODIFIERS = 'MODIFIERS',
  ORDERS = 'ORDERS',
  ORDER_STATES = 'ORDER_STATES',
  ORDER_REFUNDS = 'ORDER_REFUNDS',
  PAYMENT_METHODS = 'PAYMENT_METHODS',
  PERMISSIONS = 'PERMISSIONS',
  POS_ORDERS = 'POS_ORDERS',
  PRODUCTS = 'PRODUCTS',
  PRODUCT_SERVICES = 'PRODUCT_SERVICES',
  PRODUCT_STOCKS = 'PRODUCT_STOCKS',
  REPORT_SUMMARIES = 'REPORT_SUMMARIES',
  REPORT_SALES = 'REPORT_SALES',
  REPORT_SALES_ITEM = 'REPORT_SALES_ITEM',
  REPORT_TRANSACTIONS = 'REPORT_TRANSACTIONS',
  SERVICE_MODES = 'SERVICE_MODES',
  SERVICES = 'SERVICES',
  STAFFS = 'STAFFS',
  STAFF_INVITATIONS = 'STAFF_INVITATIONS',
  STORES = 'STORES',
  STORE_ADDRESSES = 'STORE_ADDRESSES',
  STORE_AREAS = 'STORE_AREAS',
  STORE_BILLING_HISTORIES = 'STORE_BILLING_HISTORIES',
  STORE_CUSTOMERS = 'STORE_CUSTOMERS',
  STORE_CUSTOMER_ORDERS = 'STORE_CUSTOMER_ORDERS',
  STORE_DISCOUNTS = 'STORE_DISCOUNTS',
  STORE_PAYMENT_METHODS = 'STORE_PAYMENT_METHODS',
  STORE_PREFERENCES = 'STORE_PREFERENCES',
  STORE_ROLES = 'STORE_ROLES',
  STORE_SESSIONS = 'STORE_SESSIONS',
  STORE_SUBSCRIPTIONS = 'STORE_SUBSCRIPTIONS',
  STORE_UNITS = 'STORE_UNITS',
  STORE_TAXES = 'STORE_TAXES',
  STORE_TRANSACTIONS = 'STORE_TRANSACTIONS',
  SUBSCRIPTION_PLANS = 'SUBSCRIPTION_PLANS',
}
