export enum paths {
  home = '/',
  login = '/login',
  register = '/register',
  forgotPassword = '/forgot-password',
  features = '/features',
  aboutUs = '/about-us',
  contactUs = '/contact-us',
  services = '/services',
  pricing = '/pricing',
  helpCenter = '/help-center',
  account = '/account',
  accountInfo = '/account/info',
  accountEdit = '/account/edit',
  accountInvoice = '/account/invoices',
  accountAddress = '/account/address',
  accountChangeEmail = '/account/change-email',
  accountSecurity = '/account/security',
  accountSecurityPassword = '/account/security/password',
  accountSubscription = '/account/subscription',
  accountSubscriptionChoosePlan = '/account/subscription/plans',
  accountPaymentMethodDetails = '/account/payment-methods/[id]',
}
