export enum paths {
  home = '/',
  login = '/login',
  register = '/register',
  forgotPassword = '/forgot-password',
  features = '/features',
  aboutUs = '/about-us',
  contactUs = '/contact-us',
  services = '/services',
  pricing = '/pricing',
  account = '/account',
  accountInfo = '/account/info',
  accountInfoEdit = '/account/info/edit',
  accountAddress = '/account/address',
  accountSecurity = '/account/security',
  accountSecurityPassword = '/account/security/password',
  accountSubscription = '/account/subscription',
}
