/**
 * App Endpoints
 *
 * @module Endpoints
 * @category Utils
 *
 */

export const endpoints = {
  account: {
    me: '/api/v1/account',
    update: '/api/v1/account',
    delete: '/api/v1/account',
    resendEmailVerification: '/api/v1/account/email/resend',
    changeEmail: '/api/v1/account/email/change',
    address: '/api/v1/account/address',
    createAddress: '/api/v1/account/address',
    updateAddress: '/api/v1/account/address',
    changePassword: '/api/v1/account/password',
    logout: '/api/v1/logout',

    refresh: '/api/v1/account/refresh',
    authenticateSocial: '/api/v1/account/social-login',
    sendOtp: '/api/v1/account/generate-otp',
    verifyOtp: '/api/v1/account/verify-phone-number',
    confirmEmail: '/api/v1/account/confirm-email',
  },
  accountInvoice: {
    list: '/api/v1/account/invoices',
    get: '/api/v1/account/invoices/:invoiceId',
    download: '/api/v1/account/invoices/:invoiceId/download',
  },
  accountSubscription: {
    get: '/api/v1/account/subscriptions',
    changePlan: '/api/v1/account/subscriptions/change-plan',
    reactivate: '/api/v1/account/subscriptions/reactivate',
    cancel: '/api/v1/account/subscriptions/cancel',
  },
  accountPaymentMethod: {
    session: '/api/v1/account/subscriptions/payment-methods/session',
    list: '/api/v1/account/subscriptions/payment-methods',
    create: '/api/v1/account/subscriptions/payment-methods',
    setDefault:
      '/api/v1/account/subscriptions/payment-methods/:paymentMethodId/set-default',
    delete: '/api/v1/account/subscriptions/payment-methods/:paymentMethodId',
  },
  adyen: {
    sessions: '/sessions',
  },
  auth: {
    register: '/api/v1/register',
    login: '/api/v1/login',
    logout: '/api/v1/logout',
    forgotPassword: '/api/v1/password/forgot',
    checkPassword: '/api/v1/password/check/:email/:token',
    resetPassword: '/api/v1/password/reset/:email/:token',
  },
  broadcasting: '/api/v1/broadcasting/auth',
  checkout: {
    getPaymentMethods: '/api/v1/checkout/payment-methods',
    subscribe: '/api/v1/checkout/subscribe',
    paymentMethods: '/api/v1/checkout/payment-methods',
    payment: '/api/v1/checkout/payments',
    paymentSession: '/api/v1/checkout/payments/sessions',
    paymentSessionDetails: '/api/v1/checkout/payments/sessions/:sessionId',
    paymentDetails: '/api/v1/checkout/payments/details',
  },
  coupon: {
    validate: '/api/v1/coupons/validate',
  },
  csrf: '/sanctum/csrf-cookie',
  oauth2: {
    authorize: '/oauth/authorize',
    register: '/register',
    tokens: '/oauth/tokens',
    token: '/oauth/token',
    me: '/api/v1/account/me',
    revoke: '/oauth/tokens/:token',
  },
  paymentMethod: {
    list: '/api/v1/payment-methods',
  },
  permission: {
    list: '/api/v1/permissions',
  },
  social: {
    login: '/api/v1/social/login',
    link: '/api/v1/social/link',
    unlink: '/api/v1/social/unlink',
    callback: '/api/v1/social/login/:provider/callback',
  },
  store: {
    list: '/api/v1/stores',
    create: '/api/v1/stores',
    details: '/api/v1/stores/:storeId',
    update: '/api/v1/stores/:storeId',
    classifications: '/api/v1/stores/classifications',
    enable: '/api/v1/stores/:storeId/enable',
    disable: '/api/v1/stores/:storeId/disable',
  },
  storeAddress: {
    list: '/api/v1/stores/:storeId/addresses',
    create: '/api/v1/stores/:storeId/addresses',
    details: '/api/v1/stores/:storeId/addresses/:addressId',
    primary: '/api/v1/stores/:storeId/addresses/primary',
    update: '/api/v1/stores/:storeId/addresses/:addressId',
  },
  storeArea: {
    list: '/api/v1/stores/:storeId/areas',
    create: '/api/v1/stores/:storeId/areas',
    details: '/api/v1/stores/:storeId/areas/:areaId',
    update: '/api/v1/stores/:storeId/areas/:areaId',
    delete: '/api/v1/stores/:storeId/areas/:areaId',
  },
  storeBillingHistory: {
    list: '/api/v1/stores/:storeId/billing/histories',
    download:
      '/api/v1/stores/:storeId/billing/histories/:billingHistoryId/download',
  },
  storeClassification: {
    main: '/api/v1/stores/classifications',
  },
  storeCategory: {
    list: '/api/v1/stores/:storeId/categories',
    create: '/api/v1/stores/:storeId/categories',
    deleteBulk: '/api/v1/stores/:storeId/categories',
    enable: '/api/v1/stores/:storeId/categories/enable',
    disable: '/api/v1/stores/:storeId/categories/disable',
    update: '/api/v1/stores/:storeId/categories/:categoryId',
    details: '/api/v1/stores/:storeId/categories/:categoryId',
    delete: '/api/v1/stores/:storeId/categories/:categoryId',
    import: '/api/v1/stores/:storeId/categories/import',
    export: '/api/v1/stores/:storeId/categories/export',
  },
  storeCustomer: {
    list: '/api/v1/stores/:storeId/customers',
    create: '/api/v1/stores/:storeId/customers',
    deleteBulk: '/api/v1/stores/:storeId/customers',
    update: '/api/v1/stores/:storeId/customers/:customerId',
    details: '/api/v1/stores/:storeId/customers/:customerId',
    delete: '/api/v1/stores/:storeId/customers/:customerId',
  },
  storeCustomerOrder: {
    list: '/api/v1/stores/:storeId/customers/:customerId/orders',
    details: '/api/v1/stores/:storeId/customers/:customerId/orders/:orderId',
  },
  storeDiscount: {
    list: '/api/v1/stores/:storeId/discounts',
    create: '/api/v1/stores/:storeId/discounts',
    deleteBulk: '/api/v1/stores/:storeId/discounts',
    enable: '/api/v1/stores/:storeId/discounts/enable',
    disable: '/api/v1/stores/:storeId/discounts/disable',
    update: '/api/v1/stores/:storeId/discounts/:discountId',
    details: '/api/v1/stores/:storeId/discounts/:discountId',
    delete: '/api/v1/stores/:storeId/discounts/:discountId',
    import: '/api/v1/stores/:storeId/discounts/import',
    export: '/api/v1/stores/:storeId/discounts/export',
  },
  storeEvent: {
    list: '/api/v1/stores/:storeId/events',
    create: '/api/v1/stores/:storeId/events',
    deleteBulk: '/api/v1/stores/:storeId/events',
    update: '/api/v1/stores/:storeId/events/:eventId',
    details: '/api/v1/stores/:storeId/events/:eventId',
    delete: '/api/v1/stores/:storeId/events/:eventId',
    schedule: '/api/v1/stores/:storeId/events/:eventId/schedule',
    inProgress: '/api/v1/stores/:storeId/events/:eventId/in-progress',
    complete: '/api/v1/stores/:storeId/events/:eventId/complete',
    cancel: '/api/v1/stores/:storeId/events/:eventId/cancel',
    close: '/api/v1/stores/:storeId/events/:eventId/close',
  },
  storeModifier: {
    list: '/api/v1/stores/:storeId/modifiers',
    create: '/api/v1/stores/:storeId/modifiers',
    deleteBulk: '/api/v1/stores/:storeId/modifiers',
    enable: '/api/v1/stores/:storeId/modifiers/enable',
    disable: '/api/v1/stores/:storeId/modifiers/disable',
    update: '/api/v1/stores/:storeId/modifiers/:modifierId',
    details: '/api/v1/stores/:storeId/modifiers/:modifierId',
    delete: '/api/v1/stores/:storeId/modifiers/:modifierId',
    import: '/api/v1/stores/:storeId/modifiers/import',
    export: '/api/v1/stores/:storeId/modifiers/export',
  },
  storeOrder: {
    list: '/api/v1/stores/:storeId/orders',
    create: '/api/v1/stores/:storeId/orders',
    deleteBulk: '/api/v1/stores/:storeId/orders',
    enable: '/api/v1/stores/:storeId/orders/enable',
    disable: '/api/v1/stores/:storeId/orders/disable',
    update: '/api/v1/stores/:storeId/orders/:orderId',
    details: '/api/v1/stores/:storeId/orders/:orderId',
    delete: '/api/v1/stores/:storeId/orders/:orderId',
    accept: '/api/v1/stores/:storeId/orders/:orderId/accept',
    cancel: '/api/v1/stores/:storeId/orders/:orderId/cancel',
    pay: '/api/v1/stores/:storeId/orders/:orderId/pay',
    pending: '/api/v1/stores/:storeId/orders/:orderId/pending',
    onHold: '/api/v1/stores/:storeId/orders/:orderId/hold',
    process: '/api/v1/stores/:storeId/orders/:orderId/process',
    ready: '/api/v1/stores/:storeId/orders/:orderId/ready',
    ship: '/api/v1/stores/:storeId/orders/:orderId/ship',
    void: '/api/v1/stores/:storeId/orders/:orderId/void',
    close: '/api/v1/stores/:storeId/orders/:orderId/close',
    complete: '/api/v1/stores/:storeId/orders/:orderId/complete',
    states: '/api/v1/stores/:storeId/orders/states',
  },
  storeOrderServiceMode: {
    update: '/api/v1/stores/:storeId/orders/:orderId/service-mode',
  },
  storeOrderStaff: {
    update: '/api/v1/stores/:storeId/orders/:orderId/staffs',
  },
  storeOrderReceipt: {
    send: '/api/v1/stores/:storeId/orders/:orderId/receipts/send',
  },
  storeOrderCustomer: {
    saveToStore:
      '/api/v1/stores/:storeId/orders/:orderId/customers/add-to-store',
  },
  storePaymentMethod: {
    list: '/api/v1/stores/:storeId/payment-methods',
    sync: '/api/v1/stores/:storeId/payment-methods/sync',
    details: '/api/v1/stores/:storeId/payment-methods/:paymentMethodId',
    delete: '/api/v1/stores/:storeId/payment-methods/:paymentMethodId',
    deleteBulk: '/api/v1/stores/:storeId/payment-methods',
  },
  storePosOrder: {
    list: '/api/v1/stores/:storeId/pos/orders',
  },
  storePreferences: {
    details: '/api/v1/stores/:storeId/preferences',
    update: '/api/v1/stores/:storeId/preferences',
  },
  storeProduct: {
    list: '/api/v1/stores/:storeId/products',
    create: '/api/v1/stores/:storeId/products',
    deleteBulk: '/api/v1/stores/:storeId/products',
    details: '/api/v1/stores/:storeId/products/:productId',
    update: '/api/v1/stores/:storeId/products/:productId',
    enable: '/api/v1/stores/:storeId/products/enable',
    disable: '/api/v1/stores/:storeId/products/disable',
    delete: '/api/v1/stores/:storeId/products/:productId',
    import: '/api/v1/stores/:storeId/products/import',
    export: '/api/v1/stores/:storeId/products/export',
  },
  storeProductStock: {
    list: '/api/v1/stores/:storeId/products/stocks',
    import: '/api/v1/stores/:storeId/products/stocks/import',
    export: '/api/v1/stores/:storeId/products/stocks/export',
  },
  storeProductService: {
    details: '/api/v1/stores/:storeId/product-services/:productId',
  },
  storeRefund: {
    list: '/api/v1/stores/:storeId/refunds',
    details: '/api/v1/stores/:storeId/refunds/:refundId',
    create: '/api/v1/stores/:storeId/refunds/:refundId/transactions',
  },
  storeReport: {
    summary: '/api/v1/stores/:storeId/reports/summary',
    sales: '/api/v1/stores/:storeId/reports/sales',
    salesItem: '/api/v1/stores/:storeId/reports/sales/item',
    transactionSummary: '/api/v1/stores/:storeId/reports/transactions/summary',
    transactionList: '/api/v1/stores/:storeId/reports/transactions/list',
  },
  storeService: {
    list: '/api/v1/stores/:storeId/services',
    create: '/api/v1/stores/:storeId/services',
    deleteBulk: '/api/v1/stores/:storeId/services',
    details: '/api/v1/stores/:storeId/services/:serviceId',
    update: '/api/v1/stores/:storeId/services/:serviceId',
    enable: '/api/v1/stores/:storeId/services/enable',
    disable: '/api/v1/stores/:storeId/services/disable',
    delete: '/api/v1/stores/:storeId/services/:serviceId',
    import: '/api/v1/stores/:storeId/services/import',
    export: '/api/v1/stores/:storeId/services/export',
  },
  storeServiceMode: {
    list: '/api/v1/stores/service-modes',
  },
  storeSession: {
    start: '/api/v1/stores/:storeId/sessions/start',
    end: '/api/v1/stores/:storeId/sessions/end',
    get: '/api/v1/stores/:storeId/sessions/get',
  },
  storeRole: {
    list: '/api/v1/stores/:storeId/roles',
    self: '/api/v1/stores/:storeId/roles/self',
    details: '/api/v1/stores/:storeId/roles/:roleId',
    create: '/api/v1/stores/:storeId/roles',
    update: '/api/v1/stores/:storeId/roles/:roleId',
    delete: '/api/v1/stores/:storeId/roles/:roleId',
  },
  storeSubscription: {
    details: '/api/v1/stores/:storeId/subscriptions',
  },
  storeStaff: {
    list: '/api/v1/stores/:storeId/staffs',
    deleteBulk: '/api/v1/stores/:storeId/staffs',
    details: '/api/v1/stores/:storeId/staffs/:staffId',
    update: '/api/v1/stores/:storeId/staffs/:staffId',
    delete: '/api/v1/stores/:storeId/staffs/:staffId',
  },
  storeStaffInvitation: {
    list: '/api/v1/stores/:storeId/invitations',
    resend: '/api/v1/stores/:storeId/invitations/:invitationId/resend',
    create: '/api/v1/stores/:storeId/invitations',
    delete: '/api/v1/stores/:storeId/invitations/:invitationId',
    deleteBulk: '/api/v1/stores/:storeId/invitations',
  },
  storeTax: {
    list: '/api/v1/stores/:storeId/taxes',
    details: '/api/v1/stores/:storeId/taxes/:taxId',
    create: '/api/v1/stores/:storeId/taxes',
    deleteBulk: '/api/v1/stores/:storeId/taxes',
    update: '/api/v1/stores/:storeId/taxes/:taxId',
    delete: '/api/v1/stores/:storeId/taxes/:taxId',
    import: '/api/v1/stores/:storeId/taxes/import',
    export: '/api/v1/stores/:storeId/taxes/export',
  },
  storeTransaction: {
    list: '/api/v1/stores/:storeId/transactions',
    details: '/api/v1/stores/:storeId/transactions/:transactionId',
    paid: '/api/v1/stores/:storeId/transactions/:transactionId/paid',
    cancel: '/api/v1/stores/:storeId/transactions/:transactionId/cancel',
    create: '/api/v1/stores/:storeId/transactions',
    sync: '/api/v1/stores/:storeId/transactions',
  },
  storeUnit: {
    list: '/api/v1/stores/:storeId/units',
    create: '/api/v1/stores/:storeId/units',
    details: '/api/v1/stores/:storeId/units/:unitId',
    update: '/api/v1/stores/:storeId/units/:unitId',
    status: '/api/v1/stores/:storeId/units/:unitId/status',
    delete: '/api/v1/stores/:storeId/units/:unitId',
    transfer: '/api/v1/stores/:storeId/units/transfer',
  },
  subscriptionPlan: {
    list: '/api/v1/subscriptions/plans',
  },
};

export default endpoints;
